# Generated by Django 2.1.8 on 2019-10-31 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_identity'),
        ('Shop', '0002_goods_statue'),
    ]

    operations = [

    ]
